# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Backbomb < Formula
  desc "Dockerized penetration-testing/bugbounty/app-sec testing environment"
  homepage "https://www.hahwul.com"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hahwul/backbomb/releases/download/v1.0.0/backbomb_1.0.0_darwin_amd64.tar.gz"
    sha256 "8db2fc62865dfbf571ffaf2c6add15db784333cb7ba2c9d9eff049e4607593d6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hahwul/backbomb/releases/download/v1.0.0/backbomb_1.0.0_linux_amd64.tar.gz"
    sha256 "51efc7b16c2d8dce6e3870c5a2bc40e0b6b08aa0d893718cdb8e4dad034e511d"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/hahwul/backbomb/releases/download/v1.0.0/backbomb_1.0.0_linux_armv6.tar.gz"
    sha256 "3726ad69770575bab566341237144d2d8cd239d016128d72ff66d96fcb07e689"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hahwul/backbomb/releases/download/v1.0.0/backbomb_1.0.0_linux_arm64.tar.gz"
    sha256 "ed52b8417aa061d90e9202d5bdede0e0e58b7f3684df86eeda7315911a26941d"
  end

  def install
    bin.install "backbomb"
  end

  test do
    system "#{bin}/backbomb version"
  end
end
